// VendHub.uz — Fallback / seed data
// Serves as: (1) fallback when Supabase is unavailable,
//             (2) reference for seed SQL,
//             (3) type-safe source of truth.
//
// ALL prices in UZS (integers). Main content in Russian.

import type {
  Product,
  Machine,
  Promotion,
  LoyaltyTier,
  SiteContent,
  Partner,
} from './types'

// ---------------------------------------------------------------------------
// PRODUCTS (20 total — "25+" in marketing includes seasonal/upcoming items)
// ---------------------------------------------------------------------------

export const products: Product[] = [
  // ── Coffee (8) ───────────────────────────────────────────────────────────
  {
    id: 'prod-espresso',
    name: 'Espresso',
    price: 20000,
    category: 'coffee',
    temperature: 'hot',
    popular: true,
    available: true,
    image_url: null,
    description: 'Классический крепкий эспрессо',
    rating: 4.8,
    options: [
      { name: 'С сахаром', price: 20000, temperature: 'hot' },
      { name: 'Без сахара', price: 20000, temperature: 'hot' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 1,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-americano',
    name: 'Americano',
    price: 20000,
    category: 'coffee',
    temperature: 'both',
    popular: true,
    available: true,
    image_url: null,
    description: 'Эспрессо с горячей водой',
    rating: 4.7,
    options: [
      { name: 'С сахаром', price: 20000, temperature: 'hot' },
      { name: 'Без сахара', price: 20000, temperature: 'hot' },
      { name: 'Ванильный', price: 20000, temperature: 'hot' },
      { name: 'Карамельный', price: 20000, temperature: 'hot' },
      { name: 'Без сахара', price: 20000, temperature: 'cold' },
      { name: 'Ванильный', price: 20000, temperature: 'cold' },
      { name: 'Карамельный', price: 20000, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 2,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-cappuccino',
    name: 'Cappuccino',
    price: 20000,
    category: 'coffee',
    temperature: 'both',
    popular: true,
    available: true,
    image_url: null,
    description: 'Эспрессо с молочной пенкой',
    rating: 4.9,
    options: [
      { name: 'С сахаром', price: 20000, temperature: 'hot' },
      { name: 'Без сахара', price: 20000, temperature: 'hot' },
      { name: 'Ванильный', price: 20000, temperature: 'hot' },
      { name: 'Карамельный', price: 20000, temperature: 'hot' },
      { name: 'Кокосовый', price: 20000, temperature: 'hot' },
      { name: 'Без сахара', price: 20000, temperature: 'cold' },
      { name: 'Ванильный', price: 20000, temperature: 'cold' },
      { name: 'Карамельный', price: 20000, temperature: 'cold' },
      { name: 'Кокосовый', price: 20000, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 3,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-latte',
    name: 'Latte',
    price: 20000,
    category: 'coffee',
    temperature: 'both',
    popular: true,
    available: true,
    image_url: null,
    description: 'Эспрессо с большим количеством молока',
    rating: 4.8,
    options: [
      { name: 'С сахаром', price: 20000, temperature: 'hot' },
      { name: 'Без сахара', price: 20000, temperature: 'hot' },
      { name: 'Ванильный', price: 20000, temperature: 'hot' },
      { name: 'Карамельный', price: 20000, temperature: 'hot' },
      { name: 'Кокосовый', price: 20000, temperature: 'hot' },
      { name: 'Без сахара', price: 20000, temperature: 'cold' },
      { name: 'Ванильный', price: 20000, temperature: 'cold' },
      { name: 'Карамельный', price: 20000, temperature: 'cold' },
      { name: 'Кокосовый', price: 20000, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 4,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-flat-white',
    name: 'Flat White',
    price: 25000,
    category: 'coffee',
    temperature: 'hot',
    popular: false,
    available: true,
    image_url: null,
    description: 'Двойной эспрессо с бархатистым молоком',
    rating: 4.7,
    options: [
      { name: 'Flat White', price: 25000, temperature: 'hot' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 5,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-maccoffee',
    name: 'MacCoffee 3-in-1',
    price: 10000,
    category: 'coffee',
    temperature: 'hot',
    popular: false,
    available: true,
    image_url: null,
    description: 'Растворимый кофе 3-в-1',
    rating: 4.2,
    options: [
      { name: 'MacCoffee 3-in-1', price: 10000, temperature: 'hot' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 6,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-ice-latte',
    name: 'Ice Latte',
    price: 20000,
    category: 'coffee',
    temperature: 'cold',
    popular: true,
    available: true,
    image_url: null,
    description: 'Холодный латте со льдом',
    rating: 4.8,
    options: [
      { name: 'Без сахара', price: 20000, temperature: 'cold' },
      { name: 'Ванильный', price: 20000, temperature: 'cold' },
      { name: 'Карамельный', price: 20000, temperature: 'cold' },
      { name: 'Кокосовый', price: 20000, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 7,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-ice-americano',
    name: 'Ice Americano',
    price: 20000,
    category: 'coffee',
    temperature: 'cold',
    popular: false,
    available: true,
    image_url: null,
    description: 'Холодный американо со льдом',
    rating: 4.6,
    options: [
      { name: 'Без сахара', price: 20000, temperature: 'cold' },
      { name: 'Ванильный', price: 20000, temperature: 'cold' },
      { name: 'Карамельный', price: 20000, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 8,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  // ── Tea (3) ──────────────────────────────────────────────────────────────
  {
    id: 'prod-tea-lemon',
    name: 'Чай с лимоном',
    price: 10000,
    category: 'tea',
    temperature: 'hot',
    popular: false,
    available: true,
    image_url: null,
    description: 'Чёрный чай с лимоном',
    rating: 4.5,
    options: [
      { name: 'Чай с лимоном', price: 10000, temperature: 'hot' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 9,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-tea-fruit',
    name: 'Чай фруктовый',
    price: 15000,
    category: 'tea',
    temperature: 'hot',
    popular: false,
    available: true,
    image_url: null,
    description: 'Ароматный фруктовый чай',
    rating: 4.4,
    options: [
      { name: 'Чай фруктовый', price: 15000, temperature: 'hot' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 10,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-matcha-latte',
    name: 'Matcha Latte',
    price: 30000,
    category: 'tea',
    temperature: 'both',
    popular: false,
    available: true,
    image_url: null,
    description: 'Японский чай матча с молоком',
    rating: 4.6,
    options: [
      { name: 'Matcha Latte', price: 30000, temperature: 'hot' },
    ],
    is_new: true,
    discount_percent: null,
    sort_order: 11,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },

  // ── Other (2) ────────────────────────────────────────────────────────────
  {
    id: 'prod-cocoa',
    name: 'Какао',
    price: 15000,
    category: 'other',
    temperature: 'hot',
    popular: false,
    available: true,
    image_url: null,
    description: 'Горячее какао с молоком',
    rating: 4.5,
    options: [
      { name: 'Какао', price: 15000, temperature: 'hot' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 12,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-ice',
    name: 'Лёд',
    price: 10000,
    category: 'other',
    temperature: 'cold',
    popular: false,
    available: true,
    image_url: null,
    description: 'Порция льда',
    rating: 4.0,
    options: [
      { name: 'Лёд', price: 10000, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 13,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },

  // ── Snacks (6) ───────────────────────────────────────────────────────────
  {
    id: 'prod-water',
    name: 'Вода',
    price: 5000,
    category: 'snack',
    temperature: 'cold',
    popular: false,
    available: false,
    image_url: null,
    description: 'Питьевая вода',
    rating: 4.3,
    options: [
      { name: 'Вода', price: 5000, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 14,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-cola',
    name: 'Кола',
    price: 8000,
    category: 'snack',
    temperature: 'cold',
    popular: false,
    available: false,
    image_url: null,
    description: 'Газированный напиток',
    rating: 4.4,
    options: [
      { name: 'Кола', price: 8000, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 15,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-orange-juice',
    name: 'Сок апельсин',
    price: 10000,
    category: 'snack',
    temperature: 'cold',
    popular: false,
    available: false,
    image_url: null,
    description: 'Апельсиновый сок',
    rating: 4.5,
    options: [
      { name: 'Сок апельсин', price: 10000, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 16,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-chocolate-bar',
    name: 'Шоколадный батончик',
    price: 7000,
    category: 'snack',
    temperature: 'none',
    popular: false,
    available: false,
    image_url: null,
    description: 'Шоколадный батончик',
    rating: 4.3,
    options: [
      { name: 'Шоколадный батончик', price: 7000, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 17,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-chips',
    name: 'Чипсы',
    price: 8000,
    category: 'snack',
    temperature: 'none',
    popular: false,
    available: false,
    image_url: null,
    description: 'Картофельные чипсы',
    rating: 4.2,
    options: [
      { name: 'Чипсы', price: 8000, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 18,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-croissant',
    name: 'Круассан',
    price: 12000,
    category: 'snack',
    temperature: 'none',
    popular: true,
    available: false,
    image_url: null,
    description: 'Свежий круассан',
    rating: 4.6,
    options: [
      { name: 'Круассан', price: 12000, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 19,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },

  // ── Unavailable (1) ─────────────────────────────────────────────────────
  {
    id: 'prod-frappe',
    name: 'Frappe',
    price: 26000,
    category: 'coffee',
    temperature: 'cold',
    popular: false,
    available: false,
    image_url: null,
    description: 'Холодный кофейный напиток с пенкой',
    rating: 4.5,
    options: [
      { name: 'Frappe', price: 26000, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 20,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
]

// ---------------------------------------------------------------------------
// MACHINES (16 total)
// ---------------------------------------------------------------------------

export const machines: Machine[] = [
  {
    id: 'machine-soliq-olmazor',
    name: 'SOLIQ OLMAZOR',
    address: 'Сагбон 12-й проезд 2-й тупик, 1/1',
    type: 'coffee',
    status: 'online',
    latitude: 41.3289,
    longitude: 69.2197,
    rating: 4.8,
    review_count: 42,
    floor: null,
    hours: '24/7',
    product_count: 14,
    has_promotion: true,
    location_type: 'government',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-soliq-yashnobod',
    name: 'Soliq Yashnobod',
    address: 'Шахрисабзская улица, 85',
    type: 'coffee',
    status: 'online',
    latitude: 41.2966,
    longitude: 69.2658,
    rating: 4.7,
    review_count: 38,
    floor: null,
    hours: '24/7',
    product_count: 14,
    has_promotion: true,
    location_type: 'government',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-ziyo-market',
    name: 'ZIYO market',
    address: 'Юнусабад 19-й квартал',
    type: 'coffee',
    status: 'online',
    latitude: 41.3547,
    longitude: 69.2856,
    rating: 4.6,
    review_count: 55,
    floor: null,
    hours: '24/7',
    product_count: 15,
    has_promotion: false,
    location_type: 'market',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-kpp-cardio',
    name: 'КПП Кардиология',
    address: 'Осиё улица',
    type: 'coffee',
    status: 'online',
    latitude: 41.3367,
    longitude: 69.3345,
    rating: 4.9,
    review_count: 67,
    floor: null,
    hours: '24/7',
    product_count: 14,
    has_promotion: true,
    location_type: 'hospital',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-2-corpus-cardio',
    name: '2 корпус Кардиология',
    address: 'Осиё улица, 4к2',
    type: 'coffee',
    status: 'online',
    latitude: 41.337,
    longitude: 69.3348,
    rating: 4.8,
    review_count: 45,
    floor: null,
    hours: '24/7',
    product_count: 13,
    has_promotion: false,
    location_type: 'hospital',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-4-corpus-cardio',
    name: '4 корпус Кардиология',
    address: 'Осиё улица, 4к4',
    type: 'coffee',
    status: 'offline',
    latitude: 41.3373,
    longitude: 69.3351,
    rating: 4.7,
    review_count: 31,
    floor: null,
    hours: '24/7',
    product_count: 13,
    has_promotion: false,
    location_type: 'hospital',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-american-hospital',
    name: 'American Hospital',
    address: 'Икбол, 14',
    type: 'coffee',
    status: 'online',
    latitude: 41.3135,
    longitude: 69.2791,
    rating: 4.9,
    review_count: 78,
    floor: null,
    hours: '24/7',
    product_count: 15,
    has_promotion: true,
    location_type: 'hospital',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-dunyo-supermarket',
    name: 'DUNYO Supermarket',
    address: 'Асалабад-2 жилмассив, 19',
    type: 'coffee',
    status: 'online',
    latitude: 41.27,
    longitude: 69.2106,
    rating: 4.5,
    review_count: 29,
    floor: null,
    hours: '24/7',
    product_count: 12,
    has_promotion: false,
    location_type: 'market',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-grand-clinic',
    name: 'Grand Clinic',
    address: 'Тикланиш, 1а',
    type: 'coffee',
    status: 'online',
    latitude: 41.325,
    longitude: 69.23,
    rating: 4.8,
    review_count: 52,
    floor: null,
    hours: '24/7',
    product_count: 14,
    has_promotion: false,
    location_type: 'hospital',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-kimyo',
    name: 'KIMYO',
    address: 'Улица Шота Руставели, 156',
    type: 'coffee',
    status: 'online',
    latitude: 41.3115,
    longitude: 69.2494,
    rating: 4.6,
    review_count: 63,
    floor: null,
    hours: '24/7',
    product_count: 14,
    has_promotion: false,
    location_type: 'university',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-kiut-clinic',
    name: 'KIUT CLINIC',
    address: 'Бунёдкор проспект, 19',
    type: 'coffee',
    status: 'online',
    latitude: 41.2979,
    longitude: 69.2188,
    rating: 4.7,
    review_count: 41,
    floor: null,
    hours: '24/7',
    product_count: 13,
    has_promotion: false,
    location_type: 'hospital',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-kiut-m-corp',
    name: 'KIUT M corp',
    address: 'Бунёдкор проспект, 19',
    type: 'coffee',
    status: 'online',
    latitude: 41.2982,
    longitude: 69.219,
    rating: 4.6,
    review_count: 47,
    floor: null,
    hours: '24/7',
    product_count: 14,
    has_promotion: true,
    location_type: 'university',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-kiut-library',
    name: 'KIUT Библиотека',
    address: 'Махалля Яккабог',
    type: 'coffee',
    status: 'online',
    latitude: 41.2975,
    longitude: 69.2185,
    rating: 4.8,
    review_count: 56,
    floor: null,
    hours: '24/7',
    product_count: 13,
    has_promotion: false,
    location_type: 'university',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-kiut-dorm',
    name: 'KIUT Общежитие',
    address: 'Махалля Яккабог',
    type: 'coffee',
    status: 'offline',
    latitude: 41.297,
    longitude: 69.218,
    rating: 4.5,
    review_count: 34,
    floor: null,
    hours: '24/7',
    product_count: 12,
    has_promotion: false,
    location_type: 'university',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-parus-f1',
    name: 'Parus F1',
    address: 'Катартал, 60а/1',
    type: 'coffee',
    status: 'online',
    latitude: 41.344,
    longitude: 69.352,
    rating: 4.7,
    review_count: 39,
    floor: null,
    hours: '24/7',
    product_count: 14,
    has_promotion: false,
    location_type: 'residential',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-parus-f4',
    name: 'Parus F4',
    address: 'Катартал, 60а/1',
    type: 'coffee',
    status: 'online',
    latitude: 41.3442,
    longitude: 69.3522,
    rating: 4.6,
    review_count: 27,
    floor: null,
    hours: '24/7',
    product_count: 13,
    has_promotion: false,
    location_type: 'residential',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
]

// ---------------------------------------------------------------------------
// PROMOTIONS (4 total)
// ---------------------------------------------------------------------------

export const promotions: Promotion[] = [
  {
    id: 'promo-coffee20',
    title: 'Скидка 20% на всё меню',
    badge: 'Популярное',
    description: 'Используйте промокод COFFEE20 и получите скидку 20% на любой напиток',
    promo_code: 'COFFEE20',
    gradient: 'from-red-500 to-rose-600',
    conditions: [
      'Все напитки',
      'Не суммируется с другими скидками',
      'Один раз на пользователя',
    ],
    valid_until: '2026-03-15',
    is_active: true,
    sort_order: 1,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'promo-combo',
    title: 'Комбо: Капучино + Круассан',
    badge: 'Выгодно',
    description: '45 000 → 30 000 UZS',
    promo_code: null,
    gradient: 'from-purple-500 to-violet-600',
    conditions: [
      'Капучино 300мл + Круассан',
      'Все автоматы',
    ],
    valid_until: '2026-03-31',
    is_active: true,
    sort_order: 2,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'promo-happy-hour',
    title: 'Happy Hour: -30%',
    badge: 'Ежедневно',
    description: 'Скидка 30% на холодные напитки каждый день с 14:00 до 16:00',
    promo_code: null,
    gradient: 'from-blue-500 to-indigo-600',
    conditions: [
      'Только холодные напитки',
      '14:00–16:00',
      'Все автоматы',
    ],
    valid_until: null,
    is_active: true,
    sort_order: 3,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'promo-welcome',
    title: 'x2 бонусов за первый заказ',
    badge: 'Новичкам',
    description: 'Получите двойные бонусы за первые 3 заказа с промокодом WELCOME',
    promo_code: 'WELCOME',
    gradient: 'from-amber-500 to-orange-600',
    conditions: [
      'Новые пользователи',
      'Первые 3 заказа',
    ],
    valid_until: null,
    is_active: true,
    sort_order: 4,
    created_at: '2025-01-01T00:00:00Z',
  },
]

// ---------------------------------------------------------------------------
// LOYALTY TIERS (4 total)
// ---------------------------------------------------------------------------

export const loyaltyTiers: LoyaltyTier[] = [
  {
    id: 'tier-bronze',
    level: 'Bronze',
    emoji: '\u{1F949}',
    discount_percent: 0,
    threshold: 0,
    cashback_percent: 1,
    privileges: {
      cashback: true,
      discount: false,
      priority_promos: false,
      special_codes: false,
      birthday_bonus: 0,
      early_access: false,
      personal_offers: false,
      free_drink_monthly: false,
    },
    sort_order: 1,
  },
  {
    id: 'tier-silver',
    level: 'Silver',
    emoji: '\u{1F948}',
    discount_percent: 3,
    threshold: 100000,
    cashback_percent: 1,
    privileges: {
      cashback: true,
      discount: true,
      priority_promos: true,
      special_codes: true,
      birthday_bonus: 0,
      early_access: false,
      personal_offers: false,
      free_drink_monthly: false,
    },
    sort_order: 2,
  },
  {
    id: 'tier-gold',
    level: 'Gold',
    emoji: '\u{1F947}',
    discount_percent: 5,
    threshold: 500000,
    cashback_percent: 1,
    privileges: {
      cashback: true,
      discount: true,
      priority_promos: true,
      special_codes: true,
      birthday_bonus: 20000,
      early_access: true,
      personal_offers: false,
      free_drink_monthly: false,
    },
    sort_order: 3,
  },
  {
    id: 'tier-platinum',
    level: 'Platinum',
    emoji: '\u{1F48E}',
    discount_percent: 10,
    threshold: 1000000,
    cashback_percent: 1,
    privileges: {
      cashback: true,
      discount: true,
      priority_promos: true,
      special_codes: true,
      birthday_bonus: 20000,
      early_access: true,
      personal_offers: true,
      free_drink_monthly: true,
    },
    sort_order: 4,
  },
]

// ---------------------------------------------------------------------------
// SITE CONTENT
// ---------------------------------------------------------------------------

export const siteContent: SiteContent[] = [
  { id: 'sc-hero-title', section: 'hero', key: 'title', value: 'Кофе из автоматов в пару кликов', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-hero-subtitle', section: 'hero', key: 'subtitle', value: '25+ видов напитков. 16 автоматов в больницах, университетах и общественных местах Ташкента.', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-hero-greeting-morning', section: 'hero', key: 'greeting_morning', value: '\u2600\uFE0F Доброе утро!', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-hero-greeting-afternoon', section: 'hero', key: 'greeting_afternoon', value: '\u{1F324}\uFE0F Добрый день!', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-hero-greeting-evening', section: 'hero', key: 'greeting_evening', value: '\u{1F319} Добрый вечер!', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-stats-machines', section: 'stats', key: 'machines_count', value: '16', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-stats-drinks', section: 'stats', key: 'drinks_count', value: '25+', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-stats-orders', section: 'stats', key: 'orders_count', value: '10K+', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-stats-rating', section: 'stats', key: 'rating', value: '4.8', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-about-description', section: 'about', key: 'description', value: 'VendHub — оператор сети современных кофейных и снэк-автоматов в Ташкенте. Автоматы в больницах, университетах, госучреждениях и жилых комплексах. Круглосуточный доступ к качественным горячим и холодным напиткам.', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-about-phone', section: 'about', key: 'phone', value: '+998 71 200 39 99', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-about-email', section: 'about', key: 'email', value: 'info@vendhub.uz', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-about-telegram', section: 'about', key: 'telegram', value: '@vendhub_support', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-about-address', section: 'about', key: 'address', value: 'Ташкент, Узбекистан', updated_at: '2025-01-01T00:00:00Z' },
]

// ---------------------------------------------------------------------------
// PARTNERS (5 total)
// ---------------------------------------------------------------------------

export const partners: Partner[] = [
  { id: 'partner-cardio', name: 'Респ. центр кардиологии', logo_url: null, website_url: null, description: null, sort_order: 1 },
  { id: 'partner-american-hospital', name: 'American Hospital', logo_url: null, website_url: null, description: null, sort_order: 2 },
  { id: 'partner-kiut', name: 'KIUT', logo_url: null, website_url: null, description: null, sort_order: 3 },
  { id: 'partner-grand-medical', name: 'Grand Medical', logo_url: null, website_url: null, description: null, sort_order: 4 },
]
