// VendHub.uz — Fallback / seed data
// Serves as: (1) fallback when Supabase is unavailable,
//             (2) reference for seed SQL,
//             (3) type-safe source of truth.
//
// ALL prices in UZS (integers). Main content in Russian.

import type {
  Product,
  Machine,
  Promotion,
  LoyaltyTier,
  SiteContent,
  Partner,
  BonusAction,
  LoyaltyPrivilege,
  PartnershipModel,
} from './types'

// ---------------------------------------------------------------------------
// PRODUCTS (20 total — "25+" in marketing includes seasonal/upcoming items)
// ---------------------------------------------------------------------------

export const products: Product[] = [
  // ── Coffee (8) ───────────────────────────────────────────────────────────
  {
    id: 'prod-espresso',
    name: 'Espresso',
    name_uz: 'Espresso',
    price: 20000,
    category: 'coffee',
    temperature: 'hot',
    popular: true,
    available: true,
    image_url: null,
    description: 'Классический крепкий эспрессо',
    description_uz: 'Klassik kuchli espresso',
    detail_description: '100% арабика. Концентрированный кофе, приготовленный под высоким давлением. Насыщенный вкус с плотной крема-пенкой.',
    detail_description_uz: '100% arabika. Yuqori bosim ostida tayyorlangan konsentrlangan qahva. Boy ta\'m va qalin krema ko\'pik bilan.',
    calories: 5,
    rating: 4.8,
    options: [
      { name: 'С сахаром', price: 0, temperature: 'hot' },
      { name: 'Без сахара', price: 0, temperature: 'hot' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 1,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-americano',
    name: 'Americano',
    name_uz: 'Americano',
    price: 20000,
    category: 'coffee',
    temperature: 'both',
    popular: true,
    available: true,
    image_url: null,
    description: 'Эспрессо с горячей водой',
    description_uz: 'Espresso issiq suv bilan',
    detail_description: 'Эспрессо, разбавленный горячей водой. Мягкий вкус с лёгкой кислинкой. Доступен с сахаром, ванильным и карамельным сиропом.',
    detail_description_uz: 'Issiq suv bilan suyultirilgan espresso. Engil nordonlik bilan yumshoq ta\'m. Shakar, vanil va karamel siropi bilan mavjud.',
    calories: 15,
    rating: 4.7,
    options: [
      { name: 'С сахаром', price: 0, temperature: 'hot' },
      { name: 'Без сахара', price: 0, temperature: 'hot' },
      { name: 'Ванильный', price: 0, temperature: 'hot' },
      { name: 'Карамельный', price: 0, temperature: 'hot' },
      { name: 'Без сахара', price: 0, temperature: 'cold' },
      { name: 'Ванильный', price: 0, temperature: 'cold' },
      { name: 'Карамельный', price: 0, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 2,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-cappuccino',
    name: 'Cappuccino',
    name_uz: 'Cappuccino',
    price: 20000,
    category: 'coffee',
    temperature: 'both',
    popular: true,
    available: true,
    image_url: null,
    description: 'Эспрессо с молочной пенкой',
    description_uz: 'Espresso sutli ko\'pik bilan',
    detail_description: 'Эспрессо с пышной молочной пенкой в пропорции 1:1:1. Нежный, сливочный вкус. Выбирайте классический, ванильный, карамельный или кокосовый.',
    detail_description_uz: '1:1:1 nisbatda sut ko\'pigi bilan espresso. Nozik, kremli ta\'m. Klassik, vanil, karamel yoki kokos turini tanlang.',
    calories: 120,
    rating: 4.9,
    options: [
      { name: 'С сахаром', price: 0, temperature: 'hot' },
      { name: 'Без сахара', price: 0, temperature: 'hot' },
      { name: 'Ванильный', price: 0, temperature: 'hot' },
      { name: 'Карамельный', price: 0, temperature: 'hot' },
      { name: 'Кокосовый', price: 0, temperature: 'hot' },
      { name: 'Без сахара', price: 0, temperature: 'cold' },
      { name: 'Ванильный', price: 0, temperature: 'cold' },
      { name: 'Карамельный', price: 0, temperature: 'cold' },
      { name: 'Кокосовый', price: 0, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 3,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-latte',
    name: 'Latte',
    name_uz: 'Latte',
    price: 20000,
    category: 'coffee',
    temperature: 'both',
    popular: true,
    available: true,
    image_url: null,
    description: 'Эспрессо с большим количеством молока',
    description_uz: 'Espresso ko\'p miqdorda sut bilan',
    detail_description: 'Эспрессо с большим количеством вспененного молока. Мягкий, молочный вкус идеален для тех, кто любит кофе не слишком крепким.',
    detail_description_uz: 'Ko\'p miqdorda ko\'pikli sut bilan espresso. Yumshoq, sutli ta\'m — kuchli bo\'lmagan qahvani yaxshi ko\'ruvchilar uchun ideal.',
    calories: 150,
    rating: 4.8,
    options: [
      { name: 'С сахаром', price: 0, temperature: 'hot' },
      { name: 'Без сахара', price: 0, temperature: 'hot' },
      { name: 'Ванильный', price: 0, temperature: 'hot' },
      { name: 'Карамельный', price: 0, temperature: 'hot' },
      { name: 'Кокосовый', price: 0, temperature: 'hot' },
      { name: 'Без сахара', price: 0, temperature: 'cold' },
      { name: 'Ванильный', price: 0, temperature: 'cold' },
      { name: 'Карамельный', price: 0, temperature: 'cold' },
      { name: 'Кокосовый', price: 0, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 4,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-flat-white',
    name: 'Flat White',
    name_uz: 'Flat White',
    price: 25000,
    category: 'coffee',
    temperature: 'hot',
    popular: false,
    available: true,
    image_url: null,
    description: 'Двойной эспрессо с бархатистым молоком',
    description_uz: 'Ikki espresso baxmal sut bilan',
    detail_description: 'Двойной эспрессо с тонким слоем бархатистого молока. Более крепкий и кофейный, чем латте.',
    detail_description_uz: 'Yupqa baxmal sut qatlami bilan ikki espresso. Lattega qaraganda kuchliroq va qahvali.',
    calories: 120,
    rating: 4.7,
    options: [
      { name: 'Flat White', price: 0, temperature: 'hot' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 5,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-maccoffee',
    name: 'MacCoffee 3-in-1',
    name_uz: 'MacCoffee 3-in-1',
    price: 10000,
    category: 'coffee',
    temperature: 'hot',
    popular: false,
    available: true,
    image_url: null,
    description: 'Растворимый кофе 3-в-1',
    description_uz: 'Tezkor qahva 3-in-1',
    detail_description: 'Растворимый кофе с сухим молоком и сахаром. Быстро и удобно — готов за 30 секунд.',
    detail_description_uz: 'Quruq sut va shakar bilan tezkor qahva. Tez va qulay — 30 soniyada tayyor.',
    calories: 90,
    rating: 4.2,
    options: [
      { name: 'MacCoffee 3-in-1', price: 0, temperature: 'hot' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 6,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-ice-latte',
    name: 'Ice Latte',
    name_uz: 'Ice Latte',
    price: 20000,
    category: 'coffee',
    temperature: 'cold',
    popular: true,
    available: true,
    image_url: null,
    description: 'Холодный латте со льдом',
    description_uz: 'Muzli sovuq latte',
    detail_description: 'Холодный латте со льдом. Освежающий кофейный напиток с молоком. Доступен без сахара, ванильный, карамельный и кокосовый.',
    detail_description_uz: 'Muzli sovuq latte. Sut bilan tetiklantiruvchi qahva ichimligi. Shakarsiz, vanil, karamel va kokos turlarida mavjud.',
    calories: 140,
    rating: 4.8,
    options: [
      { name: 'Без сахара', price: 0, temperature: 'cold' },
      { name: 'Ванильный', price: 0, temperature: 'cold' },
      { name: 'Карамельный', price: 0, temperature: 'cold' },
      { name: 'Кокосовый', price: 0, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 7,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-ice-americano',
    name: 'Ice Americano',
    name_uz: 'Ice Americano',
    price: 20000,
    category: 'coffee',
    temperature: 'cold',
    popular: false,
    available: true,
    image_url: null,
    description: 'Холодный американо со льдом',
    description_uz: 'Muzli sovuq americano',
    detail_description: 'Холодный американо со льдом. Чистый кофейный вкус без молока. Доступен без сахара, ванильный и карамельный.',
    detail_description_uz: 'Muzli sovuq americano. Sutsiz sof qahva ta\'mi. Shakarsiz, vanil va karamel turlarida mavjud.',
    calories: 10,
    rating: 4.6,
    options: [
      { name: 'Без сахара', price: 0, temperature: 'cold' },
      { name: 'Ванильный', price: 0, temperature: 'cold' },
      { name: 'Карамельный', price: 0, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 8,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  // ── Tea (3) ──────────────────────────────────────────────────────────────
  {
    id: 'prod-tea-lemon',
    name: 'Чай с лимоном',
    name_uz: 'Limonli choy',
    price: 10000,
    category: 'tea',
    temperature: 'hot',
    popular: false,
    available: true,
    image_url: null,
    description: 'Чёрный чай с лимоном',
    description_uz: 'Limonli qora choy',
    detail_description: 'Чёрный чай с натуральным лимоном. Классический согревающий напиток с приятной цитрусовой кислинкой.',
    detail_description_uz: 'Tabiiy limon bilan qora choy. Yoqimli sitrus nordonligi bilan klassik isituvchi ichimlik.',
    calories: 25,
    rating: 4.5,
    options: [
      { name: 'Чай с лимоном', price: 0, temperature: 'hot' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 9,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-tea-fruit',
    name: 'Чай фруктовый',
    name_uz: 'Mevali choy',
    price: 15000,
    category: 'tea',
    temperature: 'hot',
    popular: false,
    available: true,
    image_url: null,
    description: 'Ароматный фруктовый чай',
    description_uz: 'Xushbo\'y mevali choy',
    detail_description: 'Ароматный фруктовый чай из натуральных ингредиентов. Яркий вкус ягод и фруктов без кофеина.',
    detail_description_uz: 'Tabiiy ingrediyentlardan xushbo\'y mevali choy. Kofeinsiz mevalar va rezavorlarning yorqin ta\'mi.',
    calories: 35,
    rating: 4.4,
    options: [
      { name: 'Чай фруктовый', price: 0, temperature: 'hot' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 10,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-matcha-latte',
    name: 'Matcha Latte',
    name_uz: 'Matcha Latte',
    price: 30000,
    category: 'tea',
    temperature: 'both',
    popular: false,
    available: true,
    image_url: null,
    description: 'Японский чай матча с молоком',
    description_uz: 'Yaponiya matcha choyi sut bilan',
    detail_description: 'Японский зелёный чай матча, взбитый с молоком. Кремовый вкус с лёгкой горчинкой и высоким содержанием антиоксидантов.',
    detail_description_uz: 'Sut bilan ko\'pirilgan yapon yashil matcha choyi. Engil achchiqlik va yuqori antioksidant tarkibi bilan kremli ta\'m.',
    calories: 160,
    rating: 4.6,
    options: [
      { name: 'Matcha Latte', price: 0, temperature: 'hot' },
    ],
    is_new: true,
    discount_percent: null,
    sort_order: 11,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },

  // ── Other (2) ────────────────────────────────────────────────────────────
  {
    id: 'prod-cocoa',
    name: 'Какао',
    name_uz: 'Kakao',
    price: 15000,
    category: 'other',
    temperature: 'hot',
    popular: false,
    available: true,
    image_url: null,
    description: 'Горячее какао с молоком',
    description_uz: 'Sutli issiq kakao',
    detail_description: 'Горячее какао с молоком. Насыщенный шоколадный вкус, идеален в холодную погоду.',
    detail_description_uz: 'Sutli issiq kakao. Boy shokolad ta\'mi, sovuq ob-havoda ideal.',
    calories: 190,
    rating: 4.5,
    options: [
      { name: 'Какао', price: 0, temperature: 'hot' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 12,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-ice',
    name: 'Лёд',
    name_uz: 'Muz',
    price: 10000,
    category: 'other',
    temperature: 'cold',
    popular: false,
    available: true,
    image_url: null,
    description: 'Порция льда',
    description_uz: 'Bir porsiya muz',
    detail_description: 'Порция кубиков льда для любого напитка. Добавьте в кофе, чай или воду.',
    detail_description_uz: 'Har qanday ichimlik uchun muz bo\'laklari porsiyasi. Qahva, choy yoki suvga qo\'shing.',
    calories: 0,
    rating: 4.0,
    options: [
      { name: 'Лёд', price: 0, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 13,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },

  // ── Snacks (6) ───────────────────────────────────────────────────────────
  {
    id: 'prod-water',
    name: 'Вода',
    name_uz: 'Suv',
    price: 5000,
    category: 'snack',
    temperature: 'cold',
    popular: false,
    available: false,
    image_url: null,
    description: 'Питьевая вода',
    description_uz: 'Ichimlik suvi',
    detail_description: 'Чистая питьевая вода. Освежает и утоляет жажду.',
    detail_description_uz: 'Toza ichimlik suvi. Tetiklantiradi va chanqoqni qondiradi.',
    calories: 0,
    rating: 4.3,
    options: [
      { name: 'Вода', price: 0, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 14,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-cola',
    name: 'Кола',
    name_uz: 'Kola',
    price: 8000,
    category: 'snack',
    temperature: 'cold',
    popular: false,
    available: false,
    image_url: null,
    description: 'Газированный напиток',
    description_uz: 'Gazlangan ichimlik',
    detail_description: 'Классический газированный напиток. Охлаждённый, с насыщенным вкусом.',
    detail_description_uz: 'Klassik gazlangan ichimlik. Sovutilgan, boy ta\'m bilan.',
    calories: 139,
    rating: 4.4,
    options: [
      { name: 'Кола', price: 0, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 15,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-orange-juice',
    name: 'Сок апельсин',
    name_uz: 'Apelsin sharbati',
    price: 10000,
    category: 'snack',
    temperature: 'cold',
    popular: false,
    available: false,
    image_url: null,
    description: 'Апельсиновый сок',
    description_uz: 'Tabiiy apelsin sharbati',
    detail_description: 'Натуральный апельсиновый сок. Богат витамином C, освежающий цитрусовый вкус.',
    detail_description_uz: 'Tabiiy apelsin sharbati. C vitamini bilan boy, tetiklantiruvchi sitrus ta\'mi.',
    calories: 112,
    rating: 4.5,
    options: [
      { name: 'Сок апельсин', price: 0, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 16,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-chocolate-bar',
    name: 'Шоколадный батончик',
    name_uz: 'Shokolad batoncik',
    price: 7000,
    category: 'snack',
    temperature: 'none',
    popular: false,
    available: false,
    image_url: null,
    description: 'Шоколадный батончик',
    description_uz: 'Sutli shokolad batoncik',
    detail_description: 'Шоколадный батончик — сладкий перекус к кофе. Молочный шоколад с начинкой.',
    detail_description_uz: 'Shokolad batoncik — qahvaga shirin gazak. Ichki bilan sutli shokolad.',
    calories: 230,
    rating: 4.3,
    options: [
      { name: 'Шоколадный батончик', price: 0, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 17,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-chips',
    name: 'Чипсы',
    name_uz: 'Chipslar',
    price: 8000,
    category: 'snack',
    temperature: 'none',
    popular: false,
    available: false,
    image_url: null,
    description: 'Картофельные чипсы',
    description_uz: 'Kartoshka chipslari',
    detail_description: 'Хрустящие картофельные чипсы. Солёная закуска к любому напитку.',
    detail_description_uz: 'Qarsildoq kartoshka chipslari. Har qanday ichimlikka tuzli gazak.',
    calories: 270,
    rating: 4.2,
    options: [
      { name: 'Чипсы', price: 0, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 18,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-croissant',
    name: 'Круассан',
    name_uz: 'Kruassan',
    price: 12000,
    category: 'snack',
    temperature: 'none',
    popular: true,
    available: false,
    image_url: null,
    description: 'Свежий круассан',
    description_uz: 'Yangi kruassan',
    detail_description: 'Свежий слоёный круассан с маслом. Идеальное дополнение к утреннему кофе.',
    detail_description_uz: 'Sariyog\'li yangi qatlamali kruassan. Ertalabki qahvaga ideal qo\'shimcha.',
    calories: 310,
    rating: 4.6,
    options: [
      { name: 'Круассан', price: 0, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 19,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },

  // ── Unavailable (1) ─────────────────────────────────────────────────────
  {
    id: 'prod-frappe',
    name: 'Frappe',
    name_uz: 'Frappe',
    price: 26000,
    category: 'coffee',
    temperature: 'cold',
    popular: false,
    available: false,
    image_url: null,
    description: 'Холодный кофейный напиток с пенкой',
    description_uz: 'Ko\'pikli sovuq qahva ichimligi',
    detail_description: 'Холодный кофейный напиток с ледяной пенкой. Освежающий и сладкий — идеален в жаркий день.',
    detail_description_uz: 'Muzli ko\'pikli sovuq qahva ichimligi. Tetiklantiruvchi va shirin — issiq kunda ideal.',
    calories: 220,
    rating: 4.5,
    options: [
      { name: 'Frappe', price: 0, temperature: 'cold' },
    ],
    is_new: false,
    discount_percent: null,
    sort_order: 20,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
]

// ---------------------------------------------------------------------------
// MACHINES (16 total)
// ---------------------------------------------------------------------------

export const machines: Machine[] = [
  {
    id: 'machine-soliq-olmazor',
    name: 'SOLIQ OLMAZOR',
    address: 'Сагбон 12-й проезд 2-й тупик, 1/1',
    type: 'coffee',
    status: 'online',
    latitude: 41.3289,
    longitude: 69.2197,
    rating: 4.8,
    review_count: 42,
    floor: null,
    hours: '24/7',
    product_count: 14,
    has_promotion: true,
    location_type: 'government',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-soliq-yashnobod',
    name: 'Soliq Yashnobod',
    address: 'Шахрисабзская улица, 85',
    type: 'coffee',
    status: 'online',
    latitude: 41.2966,
    longitude: 69.2658,
    rating: 4.7,
    review_count: 38,
    floor: null,
    hours: '24/7',
    product_count: 14,
    has_promotion: true,
    location_type: 'government',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-ziyo-market',
    name: 'ZIYO market',
    address: 'Юнусабад 19-й квартал',
    type: 'coffee',
    status: 'online',
    latitude: 41.3547,
    longitude: 69.2856,
    rating: 4.6,
    review_count: 55,
    floor: null,
    hours: '24/7',
    product_count: 15,
    has_promotion: false,
    location_type: 'market',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-kpp-cardio',
    name: 'КПП Кардиология',
    address: 'Осиё улица',
    type: 'coffee',
    status: 'online',
    latitude: 41.3367,
    longitude: 69.3345,
    rating: 4.9,
    review_count: 67,
    floor: null,
    hours: '24/7',
    product_count: 14,
    has_promotion: true,
    location_type: 'hospital',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-2-corpus-cardio',
    name: '2 корпус Кардиология',
    address: 'Осиё улица, 4к2',
    type: 'coffee',
    status: 'online',
    latitude: 41.337,
    longitude: 69.3348,
    rating: 4.8,
    review_count: 45,
    floor: null,
    hours: '24/7',
    product_count: 13,
    has_promotion: false,
    location_type: 'hospital',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-4-corpus-cardio',
    name: '4 корпус Кардиология',
    address: 'Осиё улица, 4к4',
    type: 'coffee',
    status: 'offline',
    latitude: 41.3373,
    longitude: 69.3351,
    rating: 4.7,
    review_count: 31,
    floor: null,
    hours: '24/7',
    product_count: 13,
    has_promotion: false,
    location_type: 'hospital',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-american-hospital',
    name: 'American Hospital',
    address: 'Икбол, 14',
    type: 'coffee',
    status: 'online',
    latitude: 41.3135,
    longitude: 69.2791,
    rating: 4.9,
    review_count: 78,
    floor: null,
    hours: '24/7',
    product_count: 15,
    has_promotion: true,
    location_type: 'hospital',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-dunyo-supermarket',
    name: 'DUNYO Supermarket',
    address: 'Асалабад-2 жилмассив, 19',
    type: 'coffee',
    status: 'online',
    latitude: 41.27,
    longitude: 69.2106,
    rating: 4.5,
    review_count: 29,
    floor: null,
    hours: '24/7',
    product_count: 12,
    has_promotion: false,
    location_type: 'market',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-grand-clinic',
    name: 'Grand Clinic',
    address: 'Тикланиш, 1а',
    type: 'coffee',
    status: 'online',
    latitude: 41.325,
    longitude: 69.23,
    rating: 4.8,
    review_count: 52,
    floor: null,
    hours: '24/7',
    product_count: 14,
    has_promotion: false,
    location_type: 'hospital',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-kimyo',
    name: 'KIMYO',
    address: 'Улица Шота Руставели, 156',
    type: 'coffee',
    status: 'online',
    latitude: 41.3115,
    longitude: 69.2494,
    rating: 4.6,
    review_count: 63,
    floor: null,
    hours: '24/7',
    product_count: 14,
    has_promotion: false,
    location_type: 'university',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-kiut-clinic',
    name: 'KIUT CLINIC',
    address: 'Бунёдкор проспект, 19',
    type: 'coffee',
    status: 'online',
    latitude: 41.2979,
    longitude: 69.2188,
    rating: 4.7,
    review_count: 41,
    floor: null,
    hours: '24/7',
    product_count: 13,
    has_promotion: false,
    location_type: 'hospital',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-kiut-m-corp',
    name: 'KIUT M corp',
    address: 'Бунёдкор проспект, 19',
    type: 'coffee',
    status: 'online',
    latitude: 41.2982,
    longitude: 69.219,
    rating: 4.6,
    review_count: 47,
    floor: null,
    hours: '24/7',
    product_count: 14,
    has_promotion: true,
    location_type: 'university',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-kiut-library',
    name: 'KIUT Библиотека',
    address: 'Махалля Яккабог',
    type: 'coffee',
    status: 'online',
    latitude: 41.2975,
    longitude: 69.2185,
    rating: 4.8,
    review_count: 56,
    floor: null,
    hours: '24/7',
    product_count: 13,
    has_promotion: false,
    location_type: 'university',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-kiut-dorm',
    name: 'KIUT Общежитие',
    address: 'Махалля Яккабог',
    type: 'coffee',
    status: 'offline',
    latitude: 41.297,
    longitude: 69.218,
    rating: 4.5,
    review_count: 34,
    floor: null,
    hours: '24/7',
    product_count: 12,
    has_promotion: false,
    location_type: 'university',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-parus-f1',
    name: 'Parus F1',
    address: 'Катартал, 60а/1',
    type: 'coffee',
    status: 'online',
    latitude: 41.344,
    longitude: 69.352,
    rating: 4.7,
    review_count: 39,
    floor: null,
    hours: '24/7',
    product_count: 14,
    has_promotion: false,
    location_type: 'residential',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'machine-parus-f4',
    name: 'Parus F4',
    address: 'Катартал, 60а/1',
    type: 'coffee',
    status: 'online',
    latitude: 41.3442,
    longitude: 69.3522,
    rating: 4.6,
    review_count: 27,
    floor: null,
    hours: '24/7',
    product_count: 13,
    has_promotion: false,
    location_type: 'residential',
    image_url: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
]

// ---------------------------------------------------------------------------
// PROMOTIONS (4 total)
// ---------------------------------------------------------------------------

export const promotions: Promotion[] = [
  {
    id: 'promo-coffee20',
    title: 'Скидка 20% на всё меню',
    badge: 'Популярное',
    description: 'Используйте промокод COFFEE20 и получите скидку 20% на любой напиток',
    promo_code: 'COFFEE20',
    gradient: 'from-red-500 to-rose-600',
    conditions: ['Все напитки', 'Не суммируется с другими скидками', 'Один раз на пользователя'],
    valid_until: '2026-03-15',
    is_active: true,
    sort_order: 1,
    created_at: '2025-01-01T00:00:00Z',
    visibility_type: 'visible',
    action_instruction: '',
    discount_type: 'percent',
    discount_value: '20',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'promo-combo',
    title: 'Комбо: Капучино + Круассан',
    badge: 'Выгодно',
    description: '45 000 → 30 000 UZS',
    promo_code: null,
    gradient: 'from-purple-500 to-violet-600',
    conditions: ['Капучино 300мл + Круассан', 'Все автоматы'],
    valid_until: '2026-03-31',
    is_active: true,
    sort_order: 2,
    created_at: '2025-01-01T00:00:00Z',
    visibility_type: 'visible',
    action_instruction: '',
    discount_type: 'fixed',
    discount_value: '15 000',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'promo-welcome',
    title: 'x2 бонусов за первый заказ',
    badge: 'Новичкам',
    description: 'Получите двойные бонусы за первые 3 заказа',
    promo_code: 'WELCOME',
    gradient: 'from-amber-500 to-orange-600',
    conditions: ['Новые пользователи', 'Первые 3 заказа'],
    valid_until: null,
    is_active: true,
    sort_order: 3,
    created_at: '2025-01-01T00:00:00Z',
    visibility_type: 'action_required',
    action_instruction: 'Зарегистрируйтесь в Telegram-боте @vendhub_bot',
    discount_type: 'special',
    discount_value: 'x2 бонусов',
    updated_at: '2025-01-01T00:00:00Z',
  },
]

// ---------------------------------------------------------------------------
// LOYALTY TIERS (4 total)
// ---------------------------------------------------------------------------

export const loyaltyTiers: LoyaltyTier[] = [
  {
    id: 'tier-bronze', level: 'Bronze', emoji: '\u{1F949}',
    discount_percent: 0, threshold: 0, cashback_percent: 1,
    privileges: { cashback: true, discount: false, priority_promos: false, special_codes: false, birthday_bonus: 0, early_access: false, personal_offers: false, free_drink_monthly: false },
    sort_order: 1, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'tier-silver', level: 'Silver', emoji: '\u{1F948}',
    discount_percent: 3, threshold: 100000, cashback_percent: 1,
    privileges: { cashback: true, discount: true, priority_promos: true, special_codes: true, birthday_bonus: 0, early_access: false, personal_offers: false, free_drink_monthly: false },
    sort_order: 2, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'tier-gold', level: 'Gold', emoji: '\u{1F947}',
    discount_percent: 5, threshold: 500000, cashback_percent: 1,
    privileges: { cashback: true, discount: true, priority_promos: true, special_codes: true, birthday_bonus: 20000, early_access: true, personal_offers: false, free_drink_monthly: false },
    sort_order: 3, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'tier-platinum', level: 'Platinum', emoji: '\u{1F48E}',
    discount_percent: 10, threshold: 1000000, cashback_percent: 1,
    privileges: { cashback: true, discount: true, priority_promos: true, special_codes: true, birthday_bonus: 20000, early_access: true, personal_offers: true, free_drink_monthly: true },
    sort_order: 4, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z',
  },
]

// ---------------------------------------------------------------------------
// BONUS ACTIONS (11 total)
// ---------------------------------------------------------------------------

export const bonusActions: BonusAction[] = [
  { id: 'ba-register', title: 'Регистрация в приложении', title_uz: 'Ilovada ro\'yxatdan o\'tish', description: 'Зарегистрируйтесь в Telegram-боте @vendhub_bot', description_uz: 'Telegram-bot @vendhub_bot da ro\'yxatdan o\'ting', icon: 'Smartphone', points_amount: '20 000', type: 'earn', is_active: true, sort_order: 1, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'ba-telegram-bot', title: 'Подписка на Telegram-бот', title_uz: 'Telegram-botga obuna', description: 'Подпишитесь на @vendhub_bot', description_uz: '@vendhub_bot ga obuna bo\'ling', icon: 'Send', points_amount: '10 000', type: 'earn', is_active: true, sort_order: 2, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'ba-instagram', title: 'Подписка на Instagram', title_uz: 'Instagram obuna', description: 'Подпишитесь на @vendhub.uz в Instagram', description_uz: 'Instagramda @vendhub.uz ga obuna bo\'ling', icon: 'Camera', points_amount: '5 000', type: 'earn', is_active: true, sort_order: 3, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'ba-telegram-channel', title: 'Подписка на Telegram-канал', title_uz: 'Telegram kanalga obuna', description: 'Подпишитесь на канал @vendhub_news', description_uz: '@vendhub_news kanaliga obuna bo\'ling', icon: 'MessageCircle', points_amount: '5 000', type: 'earn', is_active: true, sort_order: 4, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'ba-phone', title: 'Верификация телефона', title_uz: 'Telefon tasdiqlash', description: 'Подтвердите номер телефона в приложении', description_uz: 'Ilovada telefon raqamingizni tasdiqlang', icon: 'Phone', points_amount: '5 000', type: 'earn', is_active: true, sort_order: 5, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'ba-cashback', title: 'Кэшбэк за покупки', title_uz: 'Xaridlar uchun keshbek', description: 'Получайте баллы за каждую покупку напитков', description_uz: 'Har bir ichimlik xaridi uchun ball oling', icon: 'Coffee', points_amount: '1%', type: 'earn', is_active: true, sort_order: 6, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'ba-referral', title: 'Приглашение друзей', title_uz: 'Do\'stlarni taklif qilish', description: 'Пригласите друга — получите оба бонус', description_uz: 'Do\'stingizni taklif qiling — ikkalangiz bonus olasiz', icon: 'UserPlus', points_amount: '5 000', type: 'earn', is_active: true, sort_order: 7, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'ba-birthday', title: 'Бонус в день рождения', title_uz: 'Tug\'ilgan kun bonusi', description: 'Тройные баллы в ваш день рождения', description_uz: 'Tug\'ilgan kuningizda uch baravar ball', icon: 'Cake', points_amount: 'x3', type: 'earn', is_active: true, sort_order: 8, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'ba-payments', title: 'Оплата заказов', title_uz: 'Buyurtmalarni to\'lash', description: 'Списывайте баллы при покупке напитков', description_uz: 'Ichimlik xarid qilganda ballarni yechib oling', icon: 'ShoppingCart', points_amount: '1 ball = 1 UZS', type: 'spend', is_active: true, sort_order: 1, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'ba-gifts', title: 'Подарки друзьям', title_uz: 'Do\'stlarga sovg\'a', description: 'Отправьте баллы другу через бот', description_uz: 'Bot orqali do\'stingizga ball yuboring', icon: 'Gift', points_amount: '1 000 dan', type: 'spend', is_active: true, sort_order: 2, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'ba-merch', title: 'Эксклюзивный мерч', title_uz: 'Eksklyuziv merch', description: 'Обменяйте баллы на фирменные товары', description_uz: 'Ballarni firmaviy tovarlarga almashing', icon: 'Star', points_amount: '50 000 dan', type: 'spend', is_active: true, sort_order: 3, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z' },
]

// ---------------------------------------------------------------------------
// LOYALTY PRIVILEGES (8 total)
// ---------------------------------------------------------------------------

export const loyaltyPrivileges: LoyaltyPrivilege[] = [
  { id: 'priv-cashback', key: 'cashback', label: 'Кэшбэк', label_uz: 'Keshbek', is_active: true, sort_order: 1, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'priv-discount', key: 'discount', label: 'Скидка на заказ', label_uz: 'Buyurtma chegirmasi', is_active: true, sort_order: 2, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'priv-priority-promos', key: 'priority_promos', label: 'Приоритетные акции', label_uz: 'Ustuvor aksiyalar', is_active: true, sort_order: 3, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'priv-special-codes', key: 'special_codes', label: 'Спецпромокоды', label_uz: 'Maxsus promokodlar', is_active: true, sort_order: 4, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'priv-birthday-bonus', key: 'birthday_bonus', label: 'Бонус на ДР', label_uz: 'Tug\'ilgan kun bonusi', is_active: true, sort_order: 5, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'priv-early-access', key: 'early_access', label: 'Ранний доступ', label_uz: 'Erta kirish', is_active: true, sort_order: 6, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'priv-personal-offers', key: 'personal_offers', label: 'Персональные предложения', label_uz: 'Shaxsiy takliflar', is_active: true, sort_order: 7, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'priv-free-drink', key: 'free_drink_monthly', label: 'Бесплатный напиток/мес', label_uz: 'Bepul ichimlik/oy', is_active: true, sort_order: 8, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z' },
]

// ---------------------------------------------------------------------------
// SITE CONTENT
// ---------------------------------------------------------------------------

export const siteContent: SiteContent[] = [
  { id: 'sc-hero-title', section: 'hero', key: 'title', value: 'Кофе из автоматов в пару кликов', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-hero-subtitle', section: 'hero', key: 'subtitle', value: '25+ видов напитков. 16 автоматов в больницах, университетах и общественных местах Ташкента.', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-hero-greeting-morning', section: 'hero', key: 'greeting_morning', value: '\u2600\uFE0F Доброе утро!', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-hero-greeting-afternoon', section: 'hero', key: 'greeting_afternoon', value: '\u{1F324}\uFE0F Добрый день!', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-hero-greeting-evening', section: 'hero', key: 'greeting_evening', value: '\u{1F319} Добрый вечер!', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-stats-machines', section: 'stats', key: 'machines_count', value: '16', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-stats-drinks', section: 'stats', key: 'drinks_count', value: '25+', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-stats-orders', section: 'stats', key: 'orders_count', value: '10K+', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-stats-rating', section: 'stats', key: 'rating', value: '4.8', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-about-description', section: 'about', key: 'description', value: 'VendHub — оператор сети современных кофейных и снэк-автоматов в Ташкенте. Автоматы в больницах, университетах, госучреждениях и жилых комплексах. Круглосуточный доступ к качественным горячим и холодным напиткам.', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-about-phone', section: 'about', key: 'phone', value: '+998 71 200 39 99', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-about-email', section: 'about', key: 'email', value: 'info@vendhub.uz', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-about-telegram', section: 'about', key: 'telegram', value: '@vendhub_support', updated_at: '2025-01-01T00:00:00Z' },
  { id: 'sc-about-address', section: 'about', key: 'address', value: 'Ташкент, Узбекистан', updated_at: '2025-01-01T00:00:00Z' },
]

// ---------------------------------------------------------------------------
// PARTNERS (5 total)
// ---------------------------------------------------------------------------

export const partners: Partner[] = [
  { id: 'partner-cardio', name: 'Респ. центр кардиологии', logo_url: null, website_url: null, description: null, sort_order: 1 },
  { id: 'partner-american-hospital', name: 'American Hospital', logo_url: null, website_url: null, description: null, sort_order: 2 },
  { id: 'partner-kiut', name: 'KIUT', logo_url: null, website_url: null, description: null, sort_order: 3 },
  { id: 'partner-grand-medical', name: 'Grand Medical', logo_url: null, website_url: null, description: null, sort_order: 4 },
]

// ---------------------------------------------------------------------------
// COLOR SCHEMES (for partnership models & reusable)
// ---------------------------------------------------------------------------

export const COLOR_SCHEMES: Record<string, { bg: string; text: string; label: string }> = {
  mint:     { bg: 'bg-mint/10',      text: 'text-mint',       label: 'Мятный' },
  caramel:  { bg: 'bg-caramel/10',   text: 'text-caramel',    label: 'Карамель' },
  espresso: { bg: 'bg-espresso/10',  text: 'text-espresso',   label: 'Эспрессо' },
  purple:   { bg: 'bg-purple-100',   text: 'text-purple-500', label: 'Фиолетовый' },
  blue:     { bg: 'bg-blue-50',      text: 'text-blue-500',   label: 'Синий' },
  red:      { bg: 'bg-red-50',       text: 'text-red-500',    label: 'Красный' },
  amber:    { bg: 'bg-amber-50',     text: 'text-amber-600',  label: 'Янтарный' },
  rose:     { bg: 'bg-rose-50',      text: 'text-rose-500',   label: 'Розовый' },
}

// ---------------------------------------------------------------------------
// PARTNERSHIP MODELS (4 total)
// ---------------------------------------------------------------------------

export const partnershipModels: PartnershipModel[] = [
  {
    id: 'pm-locations', key: 'locations', title: 'Локациям', title_uz: 'Joylashuvlar uchun',
    description: 'У вас есть помещение с трафиком? Мы установим автомат бесплатно, вы получаете процент с продаж.',
    description_uz: 'Sizda odamlar ko\'p keladigan joy bormi? Biz avtomatni bepul o\'rnatamiz, siz sotuvdan foiz olasiz.',
    icon: 'MapPin', color_scheme: 'mint',
    benefits: ['Бесплатная установка и обслуживание', 'Ежемесячные выплаты от продаж', 'Привлечение посетителей', 'Нет минимальных требований по площади'],
    benefits_uz: ['Bepul o\'rnatish va texnik xizmat', 'Sotuvdan oylik to\'lovlar', 'Tashrif buyuvchilarni jalb qilish', 'Minimal maydon talablari yo\'q'],
    is_active: true, sort_order: 1, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'pm-suppliers', key: 'suppliers', title: 'Поставщикам', title_uz: 'Yetkazib beruvchilar uchun',
    description: 'Поставляете кофе, снеки или расходники? Станьте нашим партнёром-поставщиком.',
    description_uz: 'Qahva, gazak yoki sarf materiallari yetkazib berasizmi? Bizning hamkor-yetkazib beruvchimiz bo\'ling.',
    icon: 'Package', color_scheme: 'caramel',
    benefits: ['Стабильные закупки', 'Долгосрочные контракты', 'Оплата в срок', 'Расширение географии поставок'],
    benefits_uz: ['Barqaror xaridlar', 'Uzoq muddatli shartnomalar', 'O\'z vaqtida to\'lov', 'Yetkazib berish geografiyasini kengaytirish'],
    is_active: true, sort_order: 2, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'pm-investors', key: 'investors', title: 'Инвесторам', title_uz: 'Investorlar uchun',
    description: 'Стабильный доход от сети автоматов. Окупаемость от 12 месяцев.',
    description_uz: 'Avtomat tarmog\'idan barqaror daromad. 12 oydan boshlab o\'zini qoplaydi.',
    icon: 'TrendingUp', color_scheme: 'espresso',
    benefits: ['ROI от 12 месяцев', 'Прозрачная отчётность', 'Пассивный доход', 'Масштабируемая модель'],
    benefits_uz: ['12 oydan ROI', 'Shaffof hisobot', 'Passiv daromad', 'Kengaytiriladigan model'],
    is_active: true, sort_order: 3, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'pm-franchise', key: 'franchise', title: 'Франшиза', title_uz: 'Franchayzing',
    description: 'Запустите VendHub в своём городе. Полная поддержка и обучение.',
    description_uz: 'O\'z shahringizda VendHub-ni ishga tushiring. To\'liq qo\'llab-quvvatlash va o\'qitish.',
    icon: 'Building2', color_scheme: 'purple',
    benefits: ['Готовая бизнес-модель', 'Обучение и поддержка', 'Маркетинговые материалы', 'Техническая инфраструктура'],
    benefits_uz: ['Tayyor biznes-model', 'O\'qitish va qo\'llab-quvvatlash', 'Marketing materiallari', 'Texnik infratuzilma'],
    is_active: true, sort_order: 4, created_at: '2025-01-01T00:00:00Z', updated_at: '2025-01-01T00:00:00Z',
  },
]
